version: '3.8'

services:
  oms-server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: oms-server
    env_file: ./.env
    ports:
      - "5000:5000"
    volumes:
      - ./:/app/
    depends_on:
      - oms-db

  oms-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: oms-client
    ports:
      - "3000:3000"
    volumes:
      - ./:/app/
    depends_on:
      - oms-server

  oms-db:
    image: mongo:latest
    container_name: oms-db
    env_file: ./.env
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
