version: '3.8'

services:
  oms-server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: oms-server
    env_file: ./.env
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    volumes:
      - ./:/app/
    depends_on:
      - oms-db

  oms-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: oms-client
    ports:
      - "3000:3000"
    volumes:
      - ./:/app/
    depends_on:
      - oms-server

  oms-db:
    image: mongo:latest
    container_name: oms-db
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
