name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install server dependencies
      run: npm ci
      
    - name: Install client dependencies
      working-directory: ./client
      run: npm ci --legacy-peer-dep
    
    - name: Run client linting
      working-directory: ./client
      run: npm run lint || echo "No lint script found"
    
    - name: Build client
      working-directory: ./client
      run: npm run build
      
    - name: Report success
      run: echo "CI completed successfully!"